# Generated by Django 5.0.7 on 2026-01-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitereview',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='تمت الموافقة'),
        ),
    ]
